name: Test minikube
on:
  - pull_request
  - workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build example and deploy to minikube
    steps:
    - uses: actions/checkout@v2
    - name: Start minikube
      uses: medyagh/setup-minikube@master

    - name: Try the cluster !
      run: kubectl get pods -A
    - name: Build image
      run: |
        export SHELL=/bin/bash
        docker build -t shuttershy/flask-test .
        echo -n "verifying images:"
        docker images        
    - name: Deploy to minikube
      run:
        kubectl apply -k ./k8

    - name: Wait for pods to be running
      run: kubectl wait --for=condition=Available=True deployment/flask-app

    - name: Test service URLs
      run: |
        minikube service list
        minikube service flask-app-service --url
        echo "------------------opening the service------------------"
        curl $(minikube service flask-app-service --url)        
